Link: https://www.superdatascience.com/blogs/the-ultimate-guide-to-artificial-neural-networks-ann

Part-2: https://iamtrask.github.io/2015/07/27/python-network-part2/

# Artificial Neural Network

### Importing the libraries

In [71]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [72]:
tf.__version__

'2.3.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [73]:
dataset = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Machine Learning/Deep Learning/Artificial Neural Networks(ANN)/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values #selecting from 4th to before last column of the dataframe
y = dataset.iloc[:, -1].values #selecting last column

In [74]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [75]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column - it will convert female as 0 and male as 1

In [76]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2]) #

In [77]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column - it converts categorical column into integer column by assigning 1's and 0's.

In [78]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [79]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [80]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [81]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler() #standardizing data of all columns so that all the columns have same scale
X_train = sc.fit_transform(X_train) 
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [82]:
ann = tf.keras.models.Sequential() #creating an instance of Artificial Neural Networks

### Adding the input layer and the first hidden layer

Adding the first input layer with 6 neurons and rectifier activition function - we can use any number of neurons in each layer but selecting correct number neurons depends on experimenting with different no of neurons and model accuracy then select the best neuron

In [83]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 

### Adding the second hidden layer

In [84]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

At last layer we need to have only one neuron since it is the output node. We need to select the proper activation function. As our dependent variable is binary i.e., 0 or 1. we need to use signoid function since it gives us probability of each output 

In [85]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) 

## Part 3 - Training the ANN

### Compiling the ANN

chosing appropriate optimizer and loss function is also important while modeling.

Keras optimizers: https://keras.io/api/optimizers/
Keras loss functions: https://keras.io/api/losses/

In [87]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy']) 

### Training the ANN on the Training set

In [88]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 946us/step - loss: 0.5513 - accuracy: 0.7541
Epoch 2/100
250/250 [==============================] - 0s 924us/step - loss: 0.4689 - accuracy: 0.7974
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4473 - accuracy: 0.7999
Epoch 4/100
250/250 [==============================] - 0s 989us/step - loss: 0.4351 - accuracy: 0.8030
Epoch 5/100
250/250 [==============================] - 0s 947us/step - loss: 0.4266 - accuracy: 0.8073
Epoch 6/100
250/250 [==============================] - 0s 903us/step - loss: 0.4190 - accuracy: 0.8133
Epoch 7/100
250/250 [==============================] - 0s 909us/step - loss: 0.4114 - accuracy: 0.8175
Epoch 8/100
250/250 [==============================] - 0s 920us/step - loss: 0.4048 - accuracy: 0.8219
Epoch 9/100
250/250 [==============================] - 0s 908us/step - loss: 0.3990 - accuracy: 0.8223
Epoch 10/100
250/250 [==============================] - 0s 873us/step - los

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

In [89]:
#it will give us probability of the single record
ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))

array([[0.04257306]], dtype=float32)

In [90]:
#we will make if the probability is more 0.5 than output as 1 else output as 0
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [91]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [92]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1521   74]
 [ 206  199]]


0.86